[project]
name = "snake"
version = "0.1.0"
description = "Classic snake game remake made in Python with Pygame"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame==2.6.1",
]
